Write-Host  "Tests For Interpreter"
Write-Host  ------------------------------------------ 
Write-Host  "Arithmetic Test"
.\M024.exe "test/test_arithmetic.mscf" 
Write-Host  "Boolean Test"
.\M024.exe "test/test_logical.mscf" 
Write-Host  "String Test"
.\M024.exe "test/test_strings.mscf" 
Write-Host  "Comparators Test"
.\M024.exe "test/test_comparators.mscf" 
Write-Host  "type() Test"
.\M024.exe "test/test_type.mscf" 
Write-Host  "len() Test"
.\M024.exe "test/test_len.mscf"
Write-Host "for loop Test"
.\M024.exe "test/test_for_loop.mscf"
Write-Host "function kill Test"
.\M024.exe "test/test_function_kill.mscf"
Write-Host "variable kill Test"
.\M024.exe "test/test_variable_kill.mscf"